jobs:
- name: build
  plan:
  - get: storj
    trigger: true
  - get: ci
    trigger: true
  - in_parallel:
      fail_fast: true
      steps:
      - file: ci/web.yaml
        task: web
      - file: ci/build.yaml
        task: build

resources:
- name: storj
  icon: github
  source:
    uri: https://github.com/storj/storj.git
  type: git
- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/elek/storj-ci-experiment.git
 
