jobs:
- name: build
  plan:
  - get: storj
    trigger: true
  - get: ci
    trigger: true
  - task:  pre-build
  - task: web
    file: ci/web.yaml        
  - task: build
    file: ci/build.yaml
  - task: lint
    file: ci/lint.yaml
  - task: unit
    file: ci/unit.yaml        
        

resources:
- name: storj
  icon: github
  source:
    uri: https://github.com/storj/storj.git
  type: git
- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/elek/storj-ci-experiment.git
 
